format = """\
$cmd_duration
$character\
(\
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$vcsh\
$fossil_branch\
$fossil_metrics\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
)\
(\
$directory \
$fill\
)\
( \
$package\
$c\
$cpp\
$cmake\
$cobol\
$crystal\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$gleam\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$mojo\
$nim\
$nodejs\
$ocaml\
$odin\
$opa\
$perl\
$php\
$purescript\
$python\
$quarto\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
$buf\
)\
( \
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$pulumi\
$nats\
$direnv\
$env_var\
$mise\
$pixi\
$sudo\
$jobs\
$battery\
$os\
$container\
$netns\
$shell\
$status\
$time\
$custom\
)\
$line_break\
"""

add_newline = false

[cmd_duration]
disabled = false
format = "[ â†³ ](white)executed in ğŸ•˜[$duration]($style)"
style = 'bold yellow'
show_milliseconds = true
min_time = 1

[character]
disabled = true
format = '$symbol'
success_symbol = '[ I](bold green)'
error_symbol = '[ I](bold green)'
vimcmd_symbol = '[ N](bold blue)'
vimcmd_replace_one_symbol = '[ R](bold red)'
vimcmd_replace_symbol = '[ R](bold red)'
vimcmd_visual_symbol = '[ V](bold purple)'

[username]
disabled = false
format = '[ğŸ‘¤$user ]($style)'

[hostname]
disabled = false
format = '[$ssh_symbol$hostname ]($style)'
ssh_symbol = 'ğŸŒ'

[localip]
disabled = false
format = '[ğŸ“¡$localipv4 ]($style)'

[shlvl]
disabled = false
format = '[$symbol$shlvl ]($style)'
symbol = 'ğŸ”¼'

[singularity]
disabled = false
format = '[$symbol$env ]($style)'
symbol = 'ğŸ§ª'

[kubernetes]
disabled = false
format = '[$symbol$context( \($namespace\)) ]($style)'
symbol = 'â›µ'

[vcsh]
disabled = false
format = '[$symbol$repo ]($style)'
symbol = 'ğŸ“‡'

[fossil_branch]
disabled = false
format = '[$symbol$branch ]($style)'
symbol = 'ğŸ¦'

[fossil_metrics]
disabled = false
format = '([+$added ]($added_style))([-$deleted ]($deleted_style))'

[git_branch]
disabled = false
format = '[$symbol$branch(:$remote_branch) ]($style)'
symbol = 'ğŸŒ±'
only_attached = true

[git_commit]
disabled = false
format = '[ğŸƒ$hash( $tag) ]($style)'
only_detached = true
tag_disabled = false
tag_symbol = 'ğŸ”–'

[git_state]
disabled = false
format = '[\($state( $progress_current/$progress_total)\) ]($style)'

[git_metrics]
disabled = false
format = '([+$added]($added_style))([-$deleted ]($deleted_style))'

[git_status]
disabled = false
format = '([\[$all_status$ahead_behind\] ]($style))'

[hg_branch]
disabled = false
format = '[$symbol$branch(:$topic) ]($style)'
symbol = 'ğŸª©'

[pijul_channel]
disabled = false
format = '[$symbol$channel ]($style)'
symbol = 'ğŸ¦'

[docker_context]
disabled = false
format = '[$symbol$context ]($style)'
symbol = 'ğŸ³'

[directory]
disabled = false
repo_root_format = """
[$before_root_path]($before_repo_root_style)\
[$repo_root]($repo_root_style)\
[$path]($style)\
[$read_only]($read_only_style)"""
before_repo_root_style = 'white'
repo_root_style = 'bold cyan'
format = '[$path]($style)'
style = 'bold dimmed cyan'
read_only = 'ğŸ”’'
truncate_to_repo = true
truncation_symbol = ''

[fill]
disabled = false
style = 'white'
symbol = '----===='

[package]
disabled = false
format = '[$symbol$version ]($style)'
symbol = 'ğŸ“¦'
version_format = '${raw}'

[c]
disabled = false
format = '[$symbol($version(-$name)) ]($style)'
symbol = 'ğŸŒŠ'
version_format = '${raw}'

[cpp]
disabled = false
format = '[$symbol($version(-$name)) ]($style)'
symbol = 'âœ¨'
version_format = '${raw}'

[cmake]
disabled = false
format = '[$symbol($version) ]($style)'
symbol = 'ğŸ“'
version_format = '${raw}'

[cobol]
disabled = false
format = '[$symbol($version) ]($style)'
symbol = 'ğŸ”©'
version_format = '${raw}'

[crystal]
disabled = false
format = '[$symbol($version) ]($style)'
symbol = 'ğŸ¥‚'
version_format = '${raw}'

[daml]
disabled = false
format = '[$symbol($version) ]($style)'
symbol = 'ğŸ”—'
version_format = '${raw}'

[dart]
disabled = false
format = '[$symbol($version) ]($style)'
symbol = 'ğŸ¯'
version_format = '${raw}'

[deno]
disabled = false
format = '[$symbol($version) ]($style)'
symbol = 'ğŸ¦•'
version_format = '${raw}'

[dotnet]
disabled = false
format = '[$symbol($version)( ğŸ¯$tfm) ]($style)'
symbol = 'ğŸ§©'
version_format = '${raw}'

[elixir]
disabled = false
format = '[$symbol($version ğŸ·$otp_version) ]($style)'
symbol = 'ğŸ”®'
version_format = '${raw}'

[elm]
disabled = false
format = '[$symbol($version) ]($style)'
symbol = 'ğŸŒ³'
version_format = '${raw}'

[erlang]
disabled = false
format = '[$symbol($version) ]($style)'
symbol = 'ğŸ·'
version_format = '${raw}'

[fennel]
disabled = false
format = '[$symbol($version) ]($style)'
symbol = 'ğŸ§„'
version_format = '${raw}'

[gleam]
disabled = false
format = '[$symbol($version) ]($style)'
symbol = 'â­'
version_format = '${raw}'

[golang]
disabled = false
format = '[$symbol($version) ]($style)'
symbol = 'ğŸ¹'
version_format = '${raw}'

[guix_shell]
disabled = false
format = '[$symbol($version) ]($style)'
symbol = 'ğŸƒ'

[haskell]
disabled = false
format = '[$symbol($version) ]($style)'
symbol = 'ğŸ§¬'
version_format = '${raw}'

[haxe]
disabled = false
format = '[$symbol($version) ]($style)'
symbol = 'ğŸ”¶'
version_format = '${raw}'

[helm]
disabled = false
format = '[$symbol($version) ]($style)'
symbol = 'ğŸª–'
version_format = '${raw}'

[java]
disabled = false
format = '[$symbol($version) ]($style)'
symbol = 'â˜•'
version_format = '${raw}'

[julia]
disabled = false
format = '[$symbol($version) ]($style)'
symbol = 'ğŸ’'
version_format = '${raw}'

[kotlin]
disabled = false
format = '[$symbol($version) ]($style)'
symbol = 'ğŸª¶'
version_format = '${raw}'

[gradle]
disabled = false
format = '[$symbol($version) ]($style)'
symbol = 'ğŸ”§'
version_format = '${raw}'

[lua]
disabled = false
format = '[$symbol($version) ]($style)'
symbol = 'ğŸŒ™'
version_format = '${raw}'

[mojo]
disabled = false
format = '[$symbol($version) ]($style)'
symbol = 'ğŸ”¥'

[nim]
disabled = false
format = '[$symbol($version) ]($style)'
symbol = 'ğŸ‘‘'
version_format = '${raw}'

[nodejs]
disabled = false
format = '[$symbol($version) ]($style)'
symbol = 'ğŸ¤®'
version_format = '${raw}'

[ocaml]
disabled = false
format = '[$symbol($version)( \($switch_indicator$switch_name\)) ]($style)'
symbol = 'ğŸ«'
version_format = '${raw}'

[odin]
disabled = false
format = '[$symbol($version) ]($style)'
symbol = 'ğŸª“'

[opa]
disabled = false
format = '[$symbol($version) ]($style)'
symbol = 'ğŸ”°'
version_format = '${raw}'

[perl]
disabled = false
format = '[$symbol($version) ]($style)'
symbol = 'ğŸ¦ª'
version_format = '${raw}'

[php]
disabled = false
format = '[$symbol($version) ]($style)'
symbol = 'ğŸ˜'
version_format = '${raw}'

[purescript]
disabled = false
format = '[$symbol($version) ]($style)'
symbol = 'ğŸ“œ'

[python]
disabled = false
format = '[${symbol}${pyenv_prefix}(${version})( \($virtualenv\)) ]($style)'
symbol = 'ğŸ'

[quarto]
disabled = false
format = '[$symbol($version) ]($style)'
symbol = 'ğŸ›Œ'

[raku]
disabled = false
format = '[$symbol($version-$vm_version) ]($style)'
symbol = 'ğŸ¦‹'

[rlang]
disabled = false
format = '[$symbol($version) ]($style)'
symbol = 'ğŸ“‰'

[red]
disabled = false
format = '[$symbol($version) ]($style)'
symbol = 'ğŸŸ¥'

[ruby]
disabled = false
format = '[$symbol($version) ]($style)'
symbol = 'â™¦ï¸'

[rust]
disabled = false
format = '[$symbol($version) ]($style)'
symbol = 'ğŸ¦€'

[scala]
disabled = false
format = '[$symbol($version) ]($style)'
symbol = 'ğŸªœ'

[solidity]
disabled = false
format = '[$symbol($version) ]($style)'
symbol = 'ğŸª¨'

[swift]
disabled = false
format = '[$symbol($version) ]($style)'
symbol = 'ğŸª½'

[terraform]
disabled = false
format = '[$symbol$workspace ]($style)'
symbol = 'ğŸ’ '

[typst]
disabled = false
format = '[$symbol($version) ]($style)'
symbol = 'ğŸ¹'

[vlang]
disabled = false
format = '[$symbol($version) ]($style)'
symbol = 'ğŸ––'

[vagrant]
disabled = false
format = '[$symbol($version) ]($style)'
symbol = 'ğŸš¶'

[zig]
disabled = false
format = '[$symbol($version) ]($style)'
symbol = 'ğŸ§Ÿ'

[buf]
disabled = false
format = '[$symbol($version) ]($style)'
symbol = 'ğŸª„'

[nix_shell]
disabled = false
format = '[$symbol$state( \($name\)) ]($style)'
symbol = 'â›„'

[conda]
disabled = false
format = '[$symbol$environment ]($style)'
symbol = 'ğŸ†‘'

[meson]
disabled = false
format = '[$symbol$project ]($style)'
symbol = 'ğŸŸ£'

[spack]
disabled = false
format = '[$symbol$environment ]($style)'
symbol = 'ğŸ§³'

[memory_usage]
disabled = false
format = '[$symbol${ram}(|${swap}) ]($style)'
symbol = 'ğŸ'
threshold = 85

[aws]
disabled = false
format = '[$symbol($profile)(\($region\))(\[$duration\]) ]($style)'
symbol = 'â›…'

[gcloud]
disabled = false
format = '[$symbol$account(@$domain)(\($region\)) ]($style)'
symbol = 'â›…'

[openstack]
disabled = false
format = '[$symbol$cloud(\($project\)) ]($style)'
symbol = 'â›…'

[azure]
disabled = false
format = '[$symbol($subscription) ]($style)'
symbol = 'â›…'

[pulumi]
disabled = false
format = '[$symbol($username@)$stack ]($style)'
symbol = 'â›…'

[nats]
disabled = false
format = '[$symbol$name ]($style)'
symbol = 'ğŸ’Œ'

[direnv]
disabled = false
format = '[$symbol$loaded/$allowed ]($style)'
symbol = 'ğŸ“'

[env_var]
disabled = false
format = '[$symbol$env_value ]($style)'
symbol = 'â“'

[mise]
disabled = false
format = '[$symbol$health ]($style)'
symbol = 'ğŸ³'
healthy_symbol = 'âœ…'
unhealthy_symbol = 'âŒ'

[pixi]
disabled = false
format = '[$symbol($version)(\($environment\)) ]($style)'
symbol = 'ğŸ§š'

[sudo]
disabled = false
format = '[$symbol ]($style)'
symbol = 'ğŸ§™'

[jobs]
disabled = false
format = '[$symbol$number ]($style)'
symbol = 'ğŸ‘·'

[battery]
disabled = true
format = '[$symbol$percentage ]($style)'
full_symbol = 'ğŸ”‹'
charging_symbol = 'ğŸ”Œ'
discharging_symbol = 'âš¡'
unknown_symbol = 'â“'
empty_symbol = 'ğŸª«'

[[battery.display]]
threshold = 100

[os]
disabled = true
format = '[$symbol ]($style)'

[os.symbols]
AIX = "â¿"
Alpaquita = "ğŸ””"
AlmaLinux = "ğŸ’ "
Alpine = "ğŸ—»"
Amazon = "ğŸ™‚"
Android = "ğŸ¤–"
Arch = "ğŸ—ï¸"
Artix = "ğŸ—ï¸"
Bluefin = "ğŸŸ"
CachyOS = "ğŸ—ï¸"
CentOS = "ğŸ’ "
Debian = "ğŸŒ€"
DragonFly = "ğŸ‰"
Emscripten = "ğŸ”—"
EndeavourOS = "ğŸš€"
Fedora = "ğŸ©"
FreeBSD = "ğŸ˜ˆ"
Garuda = "ğŸ¦…"
Gentoo = "ğŸ—œï¸"
HardenedBSD = "ğŸ›¡ï¸"
Illumos = "ğŸ¦"
Kali = "ğŸ‰"
Linux = "ğŸ§"
Mabox = "ğŸ“¦"
Macos = "ğŸ"
Manjaro = "ğŸ¥­"
Mariner = "ğŸŒŠ"
MidnightBSD = "ğŸŒ˜"
Mint = "ğŸŒ¿"
NetBSD = "ğŸš©"
NixOS = "â„ï¸"
Nobara = "ğŸ©"
OpenBSD = "ğŸ¡"
OpenCloudOS = "â˜ï¸"
openEuler = "ğŸ¦‰"
openSUSE = "ğŸ¦"
OracleLinux = "ğŸ¦´"
Pop = "ğŸ­"
Raspbian = "ğŸ“"
Redhat = "ğŸ©"
RedHatEnterprise = "ğŸ©"
RockyLinux = "ğŸ’ "
Redox = "ğŸ§ª"
Solus = "â›µ"
SUSE = "ğŸ¦"
Ubuntu = "ğŸ¯"
Ultramarine = "ğŸ”·"
Unknown = "â“"
Uos = "ğŸ²"
Void = "ğŸŒŒ"
Windows = "ğŸªŸ"

[container]
disabled = false
format = '[$symbol$name ]($style)'
symbol = 'ğŸ‹'

[netns]
disabled = false
format = '[$symbol$name ]($style)'
symbol = 'ğŸ›œ'

[shell]
disabled = true
format = '[ğŸ¢$indicator ]($style)'

[status]
disabled = false
format = '[$symbol$status ]($style)'
symbol = 'â—'
failure_style = 'bold red'
success_style = 'bold green'
success_symbol = 'âœ…'
not_executable_symbol = 'ğŸš«'
not_found_symbol = 'â“'
signal_symbol = 'ğŸ’¥'

[time]
disabled = true
format = '[ğŸ•’$time ]($style)'
time_format = '%H:%M:%S'

[custom]
disabled = true

[line_break]
disabled = true

