format = "[â”— exited with $status( in $cmd_duration) $fill\n\r](white)"

add_newline = false

[status]
disabled = false
format = '[$symbol$status]($style)'
symbol = 'â—'
failure_style = 'bold red'
success_style = 'bold green'
success_symbol = 'âœ…'
not_executable_symbol = 'ğŸš«'
not_found_symbol = 'â“'
signal_symbol = 'ğŸ’¥'

[cmd_duration]
disabled = false
format = "[ğŸ•˜$duration]($style)"
style = 'bold yellow'
show_milliseconds = true
min_time = 1

[fill]
disabled = false
style = 'white'
symbol = 'â”'

