format = """
[â”— finished (${custom.last_cmd} )in $cmd_duration with $status

](white)"""

add_newline = false

[custom.last_cmd]
command = 'echo $LAST_CMD'
when = '[[ -n "$LAST_CMD" ]]'
style = 'bold bright-white'
format = '[$output]($style)'

[status]
disabled = false
format = '[$symbol$status]($style)'
symbol = 'â—'
failure_style = 'bold red'
success_style = 'bold green'
success_symbol = 'âœ…'
not_executable_symbol = 'ğŸš«'
not_found_symbol = 'â“'
signal_symbol = 'ğŸ’¥'

[cmd_duration]
disabled = false
format = "[ğŸ•˜$duration]($style)"
style = 'bold yellow'
show_milliseconds = true
min_time = 1

