format = """\
$character\
([ \
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$vcsh\
$fossil_branch\
$fossil_metrics\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
](bg:bg-border))\
[ \
$directory\
$fill\
](bg:bg-middle)\
([ \
$package\
$c\
$cpp\
$cmake\
$cobol\
$crystal\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$gleam\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$mojo\
$nim\
$nodejs\
$ocaml\
$odin\
$opa\
$perl\
$php\
$purescript\
$python\
$quarto\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
$buf\
](bg:bg-border))\
([ \
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$pulumi\
$nats\
$direnv\
$env_var\
$mise\
$pixi\
$sudo\
$jobs\
$battery\
$os\
$container\
$netns\
$shell\
$status\
$time\
](black bg:green))\
$line_break"""

add_newline = false

# Builtin colors:
#
#  0. black
#  1. red
#  2. green
#  3. yellow
#  4. blue
#  5. magenta
#  6. cyan
#  7. white (off white)
#  8. bright-black (dark gray)
#  9. bright-red
# 10: bright-green
# 11: bright-yellow
# 12: bright-blue
# 13: bright-magenta
# 14: bright-cyan
# 15: bright-white

palette = 'tokyo-night-moon'

[palettes.tokyo-night-moon]
bg-border = '#3b4261'
bg-middle = '#2f334d'
bg-inactive = '0'

[custom.last_cmd]
command = 'echo $LAST_CMD'
when = '[[ -n "$LAST_CMD" ]]'
style = 'bold bright-white'
format = '[$output]($style)'

[cmd_duration]
disabled = false
format = "[ğŸ•˜$duration]($style)"
style = 'bold yellow'
show_milliseconds = true
min_time = 1

[character]
disabled = false
format = '$symbol'
success_symbol = '[ I ](bold black bg:green)'
error_symbol = '[ I ](bold black bg:green)'
vimcmd_symbol = '[ N ](bold black bg:blue)'
vimcmd_replace_one_symbol = '[ R ](bold black bg:red)'
vimcmd_replace_symbol = '[ R ](bold black bg:red)'
vimcmd_visual_symbol = '[ V ](bold black bg:purple)'

[username]
disabled = false
format = '[ğŸ‘¤$user ]($style)'
style_root = 'bold red bg:bg-border'
style_user = 'bold yellow bg:bg-border'

[hostname]
disabled = false
format = '[$ssh_symbol$hostname ]($style)'
style = 'bold dimmed green bg:bg-border'
ssh_symbol = 'ğŸŒ'

[localip]
disabled = false
format = '[ğŸ“¡](bg:bg-border)[$localipv4 ]($style)'
style = 'bold dimmed yellow bg:bg-border'

[shlvl]
disabled = false
format = '[$symbol$shlvl ]($style)'
style = 'bold yellow bg:bg-border'
symbol = 'ğŸ”¼'

[singularity]
disabled = false
format = '[$symbol](bg:bg-border)[$env ]($style)'
style = 'bold dimmed blue bg:bg-border'
symbol = 'ğŸ§ª'

[kubernetes]
disabled = false
format = '[$symbol$context( \($namespace\)) ]($style)'
style = 'bold cyan bg:bg-border'
symbol = 'â›µ'

[vcsh]
disabled = false
format = '[$symbol$repo ]($style)'
style = 'bold yellow bg:bg-border'
symbol = 'ğŸ“‡'

[fossil_branch]
disabled = false
format = '[$symbol$branch ]($style)'
style = 'bold purple bg:bg-border'
symbol = 'ğŸ¦'

[fossil_metrics]
disabled = false
format = '([+$added ]($added_style))([-$deleted ]($deleted_style))'
added_style = 'bold green bg:bg-border'
deleted_style = 'bold red bg:bg-border'

[git_branch]
disabled = false
format = '[$symbol$branch(:$remote_branch) ]($style)'
style = 'bold purple bg:bg-border'
symbol = 'ğŸŒ±'
only_attached = true

[git_commit]
disabled = false
format = '[ğŸƒ$hash( $tag) ]($style)'
style = 'bold purple bg:bg-border'
only_detached = true
tag_disabled = false
tag_symbol = 'ğŸ”–'

[git_state]
disabled = false
format = '[\($state( $progress_current/$progress_total)\) ]($style)'
style = 'bold yellow bg:bg-border'

[git_metrics]
disabled = false
format = '([+$added]($added_style))([-$deleted ]($deleted_style))'
added_style = 'bold green bg:bg-border'
deleted_style = 'bold red bg:bg-border'

[git_status]
disabled = false
format = '([\[$all_status$ahead_behind\] ]($style))'
style = 'bold red bg:bg-border'

[hg_branch]
disabled = false
format = '[$symbol$branch(:$topic) ]($style)'
style = 'bold purple bg:bg-border'
symbol = 'ğŸª©'

[pijul_channel]
disabled = false
format = '[$symbol$channel ]($style)'
style = 'bold purple bg:bg-border'
symbol = 'ğŸ¦'

[docker_context]
disabled = false
format = '[$symbol$context ]($style)'
style = 'bold blue bg:bg-border'
symbol = 'ğŸ³'

[fill]
disabled = false
style = 'bg:bg-middle'
symbol = ' '

[directory]
disabled = false
repo_root_format = """
[$before_root_path]($before_repo_root_style)\
[$repo_root]($repo_root_style)\
[$path]($style)\
[$read_only]($read_only_style)"""
before_repo_root_style = 'white bg:bg-middle'
repo_root_style = 'bold cyan bg:bg-middle'
format = '[$path]($style)'
style = 'bold dimmed cyan bg:bg-middle'
read_only = 'ğŸ”’'
truncate_to_repo = true
truncation_symbol = ''

[package]
disabled = false
format = '[$symbol$version ]($style)'
style = 'bold 208 bg:bg-border'
symbol = 'ğŸ“¦'
version_format = '${raw}'

[c]
disabled = false
format = '[$symbol($version(-$name)) ]($style)'
style = 'bold 149 bg:bg-border'
symbol = 'ğŸŒŠ'
version_format = '${raw}'

[cpp]
disabled = false
format = '[$symbol($version(-$name)) ]($style)'
style = 'bold 149 bg:bg-border'
symbol = 'âœ¨'
version_format = '${raw}'

[cmake]
disabled = false
format = '[$symbol($version) ]($style)'
style = 'bold blue bg:bg-border'
symbol = 'ğŸ“'
version_format = '${raw}'

[cobol]
disabled = false
format = '[$symbol($version) ]($style)'
style = 'bold blue bg:bg-border'
symbol = 'ğŸ”©'
version_format = '${raw}'

[crystal]
disabled = false
format = '[$symbol($version) ]($style)'
style = 'bold red bg:bg-border'
symbol = 'ğŸ¥‚'
version_format = '${raw}'

[daml]
disabled = false
format = '[$symbol($version) ]($style)'
style = 'bold cyan bg:bg-border'
symbol = 'ğŸ”—'
version_format = '${raw}'

[dart]
disabled = false
format = '[$symbol($version) ]($style)'
style = 'bold blue bg:bg-border'
symbol = 'ğŸ¯'
version_format = '${raw}'

[deno]
disabled = false
format = '[$symbol($version) ]($style)'
style = 'bold green bg:bg-border'
symbol = 'ğŸ¦•'
version_format = '${raw}'

[dotnet]
disabled = false
format = '[$symbol($version)( ğŸ¯$tfm) ]($style)'
style = 'bold blue bg:bg-border'
symbol = 'ğŸ§©'
version_format = '${raw}'

[elixir]
disabled = false
format = '[$symbol($version ğŸ·$otp_version) ]($style)'
style = 'bold purple bg:bg-border'
symbol = 'ğŸ”®'
version_format = '${raw}'

[elm]
disabled = false
format = '[$symbol($version) ]($style)'
style = 'bold cyan bg:bg-border'
symbol = 'ğŸŒ³'
version_format = '${raw}'

[erlang]
disabled = false
format = '[$symbol($version) ]($style)'
style = 'bold red bg:bg-border'
symbol = 'ğŸ·'
version_format = '${raw}'

[fennel]
disabled = false
format = '[$symbol($version) ]($style)'
style = 'bold green bg:bg-border'
symbol = 'ğŸ§„'
version_format = '${raw}'

[gleam]
disabled = false
format = '[$symbol($version) ]($style)'
style = 'bold #FFAFF3 bg:bg-border'
symbol = 'â­'
version_format = '${raw}'

[golang]
disabled = false
format = '[$symbol($version) ]($style)'
style = 'bold cyan bg:bg-border'
not_capable_style = 'bold red bg:bg-border'
symbol = 'ğŸ¹'
version_format = '${raw}'

[guix_shell]
disabled = false
format = '[$symbol($version) ]($style)'
style = 'bold yellow bg:bg-border'
symbol = 'ğŸƒ'

[haskell]
disabled = false
format = '[$symbol($version) ]($style)'
style = 'bold purple bg:bg-border'
symbol = 'ğŸ§¬'
version_format = '${raw}'

[haxe]
disabled = false
format = '[$symbol($version) ]($style)'
style = 'bold 202 bg:bg-border'
symbol = 'ğŸ”¶'
version_format = '${raw}'

[helm]
disabled = false
format = '[$symbol($version) ]($style)'
style = 'bold white bg:bg-border'
symbol = 'ğŸª–'
version_format = '${raw}'

[java]
disabled = false
format = '[$symbol($version) ]($style)'
style = 'bold dimmed red bg:bg-border'
symbol = 'â˜•'
version_format = '${raw}'

[julia]
disabled = false
format = '[$symbol($version) ]($style)'
style = 'bold purple bg:bg-border'
symbol = 'ğŸ’'
version_format = '${raw}'

[kotlin]
disabled = false
format = '[$symbol($version) ]($style)'
style = 'bold blue bg:bg-border'
symbol = 'ğŸª¶'
version_format = '${raw}'

[gradle]
disabled = false
format = '[$symbol($version) ]($style)'
style = 'bold bright-cyan bg:bg-border'
symbol = 'ğŸ”§'
version_format = '${raw}'

[lua]
disabled = false
format = '[$symbol($version) ]($style)'
style = 'bold blue bg:bg-border'
symbol = 'ğŸŒ™'
version_format = '${raw}'

[mojo]
disabled = false
format = '[$symbol($version) ]($style)'
style = 'bold 208 bg:bg-border'
symbol = 'ğŸ”¥'

[nim]
disabled = false
format = '[$symbol($version) ]($style)'
style = 'bold yellow bg:bg-border'
symbol = 'ğŸ‘‘'
version_format = '${raw}'

[nodejs]
disabled = false
format = '[$symbol($version) ]($style)'
style = 'bold green bg:bg-border'
symbol = 'ğŸ¤¢'
version_format = '${raw}'

[ocaml]
disabled = false
format = '[$symbol($version)( \($switch_indicator$switch_name\)) ]($style)'
style = 'bold yellow bg:bg-border'
symbol = 'ğŸ«'
version_format = '${raw}'

[odin]
disabled = false
format = '[$symbol($version) ]($style)'
style = 'bold cyan bg:bg-border'
symbol = 'ğŸª“'

[opa]
disabled = false
format = '[$symbol($version) ]($style)'
style = 'bold blue bg:bg-border'
symbol = 'ğŸ”°'
version_format = '${raw}'

[perl]
disabled = false
format = '[$symbol($version) ]($style)'
style = 'bold 149 bg:bg-border'
symbol = 'ğŸ¦ª'
version_format = '${raw}'

[php]
disabled = false
format = '[$symbol($version) ]($style)'
style = 'bold 147 bg:bg-border'
symbol = 'ğŸ˜'
version_format = '${raw}'

[purescript]
disabled = false
format = '[$symbol($version) ]($style)'
style = 'bold white bg:bg-border'
symbol = 'ğŸ“œ'

[python]
disabled = false
format = '[${symbol}${pyenv_prefix}(${version})( \($virtualenv\)) ]($style)'
style = 'bold yellow bg:bg-border'
symbol = 'ğŸ'

[quarto]
disabled = false
format = '[$symbol($version) ]($style)'
style = 'bold #75AADB bg:bg-border'
symbol = 'ğŸ›Œ'

[raku]
disabled = false
format = '[$symbol($version-$vm_version) ]($style)'
style = 'bold 149 bg:bg-border'
symbol = 'ğŸ¦‹'

[rlang]
disabled = false
format = '[$symbol($version) ]($style)'
style = 'bold blue bg:bg-border'
symbol = 'ğŸ“‰'

[red]
disabled = false
format = '[$symbol($version) ]($style)'
style = 'bold red bg:bg-border'
symbol = 'ğŸŸ¥'

[ruby]
disabled = false
format = '[$symbol($version) ]($style)'
style = 'bold red bg:bg-border'
symbol = 'â™¦ï¸'

[rust]
disabled = false
format = '[$symbol($version) ]($style)'
style = 'bold red bg:bg-border'
symbol = 'ğŸ¦€'

[scala]
disabled = false
format = '[$symbol($version) ]($style)'
style = 'bold dimmed red bg:bg-border'
symbol = 'ğŸªœ'

[solidity]
disabled = false
format = '[$symbol($version) ]($style)'
style = 'bold blue bg:bg-border'
symbol = 'ğŸª¨'

[swift]
disabled = false
format = '[$symbol($version) ]($style)'
style = 'bold 202 bg:bg-border'
symbol = 'ğŸª½'

[terraform]
disabled = false
format = '[$symbol$workspace ]($style)'
style = 'bold 105 bg:bg-border'
symbol = 'ğŸ’ '

[typst]
disabled = false
format = '[$symbol($version) ]($style)'
style = 'bold #0093A7 bg:bg-border'
symbol = 'ğŸ¹'

[vlang]
disabled = false
format = '[$symbol($version) ]($style)'
style = 'bold blue bg:bg-border'
symbol = 'ğŸ––'

[vagrant]
disabled = false
format = '[$symbol($version) ]($style)'
style = 'bold cyan bg:bg-border'
symbol = 'ğŸš¶'

[zig]
disabled = false
format = '[$symbol($version) ]($style)'
style = 'bold yellow bg:bg-border'
symbol = 'ğŸ§Ÿ'

[buf]
disabled = false
format = '[$symbol($version) ]($style)'
style = 'bold black bg:green'
symbol = 'ğŸª„'

[nix_shell]
disabled = false
format = '[$symbol$state( \($name\)) ]($style)'
style = 'bold black bg:green'
symbol = 'â›„'

[conda]
disabled = false
format = '[$symbol$environment ]($style)'
style = 'bold black bg:green'
symbol = 'ğŸ†‘'

[meson]
disabled = false
format = '[$symbol$project ]($style)'
style = 'bold black bg:green'
symbol = 'ğŸŸ£'

[spack]
disabled = false
format = '[$symbol$environment ]($style)'
style = 'bold black bg:green'
symbol = 'ğŸ§³'

[memory_usage]
disabled = false
format = '[$symbol${ram}(|${swap}) ]($style)'
style = 'bold black bg:green'
symbol = 'ğŸ'
threshold = 85

[aws]
disabled = false
format = '[$symbol($profile)(\($region\))(\[$duration\]) ]($style)'
style = 'bold black bg:green'
symbol = 'â›…'

[gcloud]
disabled = false
format = '[$symbol$account(@$domain)(\($region\)) ]($style)'
style = 'bold black bg:green'
symbol = 'â›…'

[openstack]
disabled = false
format = '[$symbol$cloud(\($project\)) ]($style)'
style = 'bold black bg:green'
symbol = 'â›…'

[azure]
disabled = false
format = '[$symbol($subscription) ]($style)'
style = 'bold black bg:green'
symbol = 'â›…'

[pulumi]
disabled = false
format = '[$symbol($username@)$stack ]($style)'
style = 'bold magenta bg:bg-border'
symbol = 'â›…'

[nats]
disabled = false
format = '[$symbol$name ]($style)'
style = 'bold black bg:green'
symbol = 'ğŸ’Œ'

[direnv]
disabled = false
format = '[$symbol$loaded/$allowed ]($style)'
style = 'bold black bg:green'
symbol = 'ğŸ“'

[env_var]
disabled = false
format = '[$symbol$env_value ]($style)'
style = 'bold black bg:green'
symbol = 'â“'

[mise]
disabled = false
format = '[$symbol$health ]($style)'
style = 'bold black bg:green'
symbol = 'ğŸ³'
healthy_symbol = 'âœ…'
unhealthy_symbol = 'âŒ'

[pixi]
disabled = false
format = '[$symbol($version)(\($environment\)) ]($style)'
style = 'bold black bg:green'
symbol = 'ğŸ§š'

[sudo]
disabled = false
format = '[$symbol ]($style)'
style = 'bold black bg:green'
symbol = 'ğŸ§™'

[jobs]
disabled = false
format = '[$symbol$number ]($style)'
style = 'bold black bg:green'
symbol = 'ğŸ‘·'

[battery]
disabled = true
format = '[$symbol$percentage ]($style)'
style = 'bold black bg:green'
full_symbol = 'ğŸ”‹'
charging_symbol = 'ğŸ”Œ'
discharging_symbol = 'âš¡'
unknown_symbol = 'â“'
empty_symbol = 'ğŸª«'

[[battery.display]]
threshold = 100
style = 'bold black bg:green'

[os]
disabled = true
format = '[$symbol ]($style)'
style = 'bold black bg:green'

[os.symbols]
AIX = "â¿"
Alpaquita = "ğŸ””"
AlmaLinux = "ğŸ’ "
Alpine = "ğŸ—»"
Amazon = "ğŸ™‚"
Android = "ğŸ¤–"
Arch = "ğŸ—ï¸"
Artix = "ğŸ—ï¸"
Bluefin = "ğŸŸ"
CachyOS = "ğŸ—ï¸"
CentOS = "ğŸ’ "
Debian = "ğŸŒ€"
DragonFly = "ğŸ‰"
Emscripten = "ğŸ”—"
EndeavourOS = "ğŸš€"
Fedora = "ğŸ©"
FreeBSD = "ğŸ˜ˆ"
Garuda = "ğŸ¦…"
Gentoo = "ğŸ—œï¸"
HardenedBSD = "ğŸ›¡ï¸"
Illumos = "ğŸ¦"
Kali = "ğŸ‰"
Linux = "ğŸ§"
Mabox = "ğŸ“¦"
Macos = "ğŸ"
Manjaro = "ğŸ¥­"
Mariner = "ğŸŒŠ"
MidnightBSD = "ğŸŒ˜"
Mint = "ğŸŒ¿"
NetBSD = "ğŸš©"
NixOS = "â„ï¸"
Nobara = "ğŸ©"
OpenBSD = "ğŸ¡"
OpenCloudOS = "â˜ï¸"
openEuler = "ğŸ¦‰"
openSUSE = "ğŸ¦"
OracleLinux = "ğŸ¦´"
Pop = "ğŸ­"
Raspbian = "ğŸ“"
Redhat = "ğŸ©"
RedHatEnterprise = "ğŸ©"
RockyLinux = "ğŸ’ "
Redox = "ğŸ§ª"
Solus = "â›µ"
SUSE = "ğŸ¦"
Ubuntu = "ğŸ¯"
Ultramarine = "ğŸ”·"
Unknown = "â“"
Uos = "ğŸ²"
Void = "ğŸŒŒ"
Windows = "ğŸªŸ"

[container]
disabled = false
format = '[$symbol$name ]($style)'
style = 'bold black bg:green'
symbol = 'ğŸ‹'

[netns]
disabled = false
format = '[$symbol$name ]($style)'
style = 'bold black bg:green'
symbol = 'ğŸ›œ'

[shell]
disabled = true
format = '[ğŸ¢$indicator ]($style)'
style = 'bold black bg:green'

[status]
disabled = false
format = '[$symbol$status ]($style)'
symbol = 'â—'
failure_style = 'bold black bg:green'
success_style = 'bold black bg:green'
success_symbol = 'âœ…'
not_executable_symbol = 'ğŸš«'
not_found_symbol = 'â“'
signal_symbol = 'ğŸ’¥'

[time]
disabled = true
format = '[ğŸ•’$time ]($style)'
style = 'bold black bg:green'
time_format = '%H:%M:%S'

[line_break]
disabled = false
